version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16.3-stretch-browsers

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
      - run:
          name: ESLint Code Analysis
          command: yarn lint

  typecheck:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Typechecking with flow
          command: yarn typecheck

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test

  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests and upload coverage results
          command: yarn test:coverage

  prettier:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Check prettier diff
          command: yarn prettier:diff

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build all distributions formats
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - typecheck:
          requires:
            - dependencies
      - prettier:
          requires:
            - dependencies
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages
      - coverage:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages
